// <auto-generated />
using System;
using Encrypz.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Encrypz.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260827170148_GoogleDriveIntegration")]
    partial class GoogleDriveIntegration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Encrypz.Core.Entities.EncryptedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte[]>("AuthenticationTag")
                        .IsRequired()
                        .HasColumnType("VARBINARY(16)");

                    b.Property<byte[]>("EncryptedFileName")
                        .IsRequired()
                        .HasColumnType("VARBINARY(512)");

                    b.Property<string>("GoogleDriveFileId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<byte[]>("InitializationVector")
                        .IsRequired()
                        .HasColumnType("VARBINARY(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EncryptedFiles");
                });

            modelBuilder.Entity("Encrypz.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("GoogleRefreshToken")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Encrypz.Core.Entities.EncryptedFile", b =>
                {
                    b.HasOne("Encrypz.Core.Entities.User", "User")
                        .WithMany("EncryptedFiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Encrypz.Core.Entities.User", b =>
                {
                    b.Navigation("EncryptedFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
